"""Alert model for NetWatch AI."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.mixins import TimestampMixin

if TYPE_CHECKING:
    from app.models.alert_evidence import AlertEvidence
    from app.models.ai_insight import AiInsight
    from app.models.detection_rule import DetectionRule
    from app.models.device import Device


class Alert(TimestampMixin, Base):
    """A security finding generated by the detection and correlation engine.

    Attributes:
        rule_id: Triggering detection rule (optional).
        device_id: Main affected device (optional).
        source_ip / destination_ip: Involved endpoints.
        title / description: Human-readable summary.
        severity: ``critical``, ``high``, ``medium``, or ``low``.
        risk_score / confidence: 0-100 numeric values.
        status: The alert lifecycle state. ``open``, ``acknowledged``,
            ``resolved``, ``dismissed`` or ``false_positive``, as
            :mod:`app.alerts.status` defines it (M11.6). The legacy M2 names
            ``new`` and ``investigating`` are still *accepted* by the CHECK so a
            pre-M11 row remains valid, but nothing writes them any more.
        correlation_key: The deduplication key of the incident this alert
            belongs to (M11.9), which is also where the detector's string rule
            id is carried.
        resolved_at: When the alert reached a terminal state (optional).
    """

    # ``risk_score`` is retained because M2 defined the column and later
    # milestones populate it. No M11 code writes it: risk needs the historical
    # context M12 owns, and M11 states severity and confidence only.
    # ``status`` defaults to ``open``, the M11 lifecycle's initial state. The
    # database default of a pre-existing table is not altered by a model change,
    # which is harmless because the alert service always writes the status
    # explicitly (M11.3) — this only governs rows created outside it.

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    rule_id: Mapped[int | None] = mapped_column(
        ForeignKey("detection_rules.id", ondelete="SET NULL"),
        nullable=True,
    )
    device_id: Mapped[int | None] = mapped_column(
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )
    source_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    destination_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    risk_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    confidence: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="open")

    correlation_key: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    device: Mapped["Device"] = relationship(back_populates="alerts")
    rule: Mapped["DetectionRule"] = relationship(back_populates="alerts")
    evidence_records: Mapped[list["AlertEvidence"]] = relationship(
        back_populates="alert",
        cascade="all, delete-orphan",
    )
    ai_insights: Mapped[list["AiInsight"]] = relationship(back_populates="alert")

    __table_args__ = (
        CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low')",
            name="ck_alerts_severity",
        ),
        # The M11 lifecycle values first, then the legacy M2 names so a pre-M11
        # row stays valid. The order mirrors ``app.alerts.status``'s
        # ``STORED_STATUS_VALUES`` exactly — as a single unbroken line — so the
        # constraint a *fresh* database gets is byte-identical to the one
        # ``upgrade_alert_status_constraint`` produces. That is what lets the
        # upgrade recognise a current schema as a no-op instead of rebuilding it.
        CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved', 'dismissed', 'false_positive', 'new', 'investigating')",
            name="ck_alerts_status",
        ),
        CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100",
            name="ck_alerts_risk_score",
        ),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name="ck_alerts_confidence",
        ),
        Index("idx_alerts_created_at", "created_at"),
        Index("idx_alerts_severity", "severity"),
        Index("idx_alerts_status", "status"),
        Index("idx_alerts_device_id", "device_id"),
        Index("idx_alerts_rule_id", "rule_id"),
    )
