"""Alert model for NetWatch AI."""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.models.mixins import TimestampMixin

if TYPE_CHECKING:
    from app.models.alert_evidence import AlertEvidence
    from app.models.ai_insight import AiInsight
    from app.models.detection_rule import DetectionRule
    from app.models.device import Device


class Alert(TimestampMixin, Base):
    """A security finding generated by the detection and correlation engine.

    Attributes:
        rule_id: Triggering detection rule (optional).
        device_id: Main affected device (optional).
        source_ip / destination_ip: Involved endpoints.
        title / description: Human-readable summary.
        severity: ``critical``, ``high``, ``medium``, or ``low``.
        risk_score / confidence: 0-100 numeric values.
        status: ``new``, ``acknowledged``, ``investigating``, ``resolved``,
            or ``false_positive``.
        correlation_key: Optional key used to deduplicate related alerts.
        resolved_at: When the alert was resolved (optional).
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    rule_id: Mapped[int | None] = mapped_column(
        ForeignKey("detection_rules.id", ondelete="SET NULL"),
        nullable=True,
    )
    device_id: Mapped[int | None] = mapped_column(
        ForeignKey("devices.id", ondelete="SET NULL"),
        nullable=True,
    )
    source_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    destination_ip: Mapped[str | None] = mapped_column(String(45), nullable=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    risk_score: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    confidence: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="new")

    correlation_key: Mapped[str | None] = mapped_column(String(255), nullable=True, index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    device: Mapped["Device"] = relationship(back_populates="alerts")
    rule: Mapped["DetectionRule"] = relationship(back_populates="alerts")
    evidence_records: Mapped[list["AlertEvidence"]] = relationship(
        back_populates="alert",
        cascade="all, delete-orphan",
    )
    ai_insights: Mapped[list["AiInsight"]] = relationship(back_populates="alert")

    __table_args__ = (
        CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low')",
            name="ck_alerts_severity",
        ),
        CheckConstraint(
            "status IN ('new', 'acknowledged', 'investigating', 'resolved', 'false_positive')",
            name="ck_alerts_status",
        ),
        CheckConstraint(
            "risk_score >= 0 AND risk_score <= 100",
            name="ck_alerts_risk_score",
        ),
        CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name="ck_alerts_confidence",
        ),
        Index("idx_alerts_created_at", "created_at"),
        Index("idx_alerts_severity", "severity"),
        Index("idx_alerts_status", "status"),
        Index("idx_alerts_device_id", "device_id"),
        Index("idx_alerts_rule_id", "rule_id"),
    )
